# SPDX-License-Identifier: GPL-2.0
"""Build the guest image: busybox initramfs + kbuf.ko + static test binaries.

The image is built once per pytest session and reused by every boot.  Guest
behaviour is selected at boot time through kernel command-line parameters
parsed by the generic /init below:

    kbuf.ndevices=N   insmod kbuf.ko ndevices=N   (default: module default)
    kbuf.noinsmod     skip insmod (the workload does its own module handling)
    kbuf.cmd=PATH[,ARG...]   workload to run; commas become argv separators
    kbuf.timeout=SEC  guest-side timeout around the workload (default 30)

Every boot emits structured markers on the serial console:

    KBUF_VERIF: boot kernel=...
    KBUF_VERIF: insmod rc=N
    KBUF_VERIF: cmd rc=N
    KBUF_VERIF: dmesg-begin ... dmesg-end
    KBUF_VERIF: done
"""

import shutil
import subprocess
from pathlib import Path

APPLETS = (
    "sh mount insmod rmmod cat ls echo sleep poweroff dmesg mkdir "
    "timeout grep wc tr kill head sed"
).split()

INIT = r"""#!/bin/sh
# kbuf verification guest (PID 1). Generated by kbufverif/initramfs.py.
/bin/busybox mount -t devtmpfs none /dev 2>/dev/null
exec 0</dev/console 1>/dev/console 2>/dev/console
export PATH=/bin
mount -t proc  none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug 2>/dev/null

CMD= NDEV= TMO=30 NOINSMOD=0
for tok in $(cat /proc/cmdline); do
	case "$tok" in
	kbuf.cmd=*)      CMD="${tok#kbuf.cmd=}" ;;
	kbuf.ndevices=*) NDEV="${tok#kbuf.ndevices=}" ;;
	kbuf.timeout=*)  TMO="${tok#kbuf.timeout=}" ;;
	kbuf.noinsmod)   NOINSMOD=1 ;;
	esac
done

echo "KBUF_VERIF: boot kernel=$(uname -r)"

if [ "$NOINSMOD" = 0 ]; then
	if [ -n "$NDEV" ]; then
		insmod /kbuf.ko ndevices="$NDEV"
	else
		insmod /kbuf.ko
	fi
	echo "KBUF_VERIF: insmod rc=$?"
fi

if [ -n "$CMD" ]; then
	CMD="$(echo "$CMD" | tr ',' ' ')"
	timeout "$TMO" $CMD
	echo "KBUF_VERIF: cmd rc=$?"
fi

echo "KBUF_VERIF: dmesg-begin"
dmesg
echo "KBUF_VERIF: dmesg-end"
echo "KBUF_VERIF: done"
poweroff -f
"""


def _check(cmd, **kw):
    return subprocess.run(cmd, check=True, capture_output=True, text=True, **kw)


def find_busybox():
    bb = shutil.which("busybox")
    if not bb:
        raise RuntimeError(
            "busybox not found (sudo apt-get install -y busybox-static)")
    out = _check(["file", "-L", bb]).stdout
    if "statically linked" not in out:
        raise RuntimeError(f"busybox at {bb} is not static "
                           "(install busybox-static)")
    return bb


def build_image(repo: Path, build_dir: Path, kdir: Path = None) -> Path:
    """Build module + static tests + initramfs; return the cpio.gz path.

    When ``kdir`` is given the module is built against that kernel tree (a
    debug-variant build) so its layout matches the guest kernel that will load
    it; otherwise it builds against the running kernel's headers.
    """
    repo = Path(repo)
    build_dir = Path(build_dir)
    root = build_dir / "verif-initramfs"
    out = build_dir / "verif-initramfs.cpio.gz"

    make_modules = ["make", "-C", str(repo), "modules"]
    if kdir is not None:
        make_modules.append(f"KDIR={kdir}")
    _check(make_modules)

    if root.exists():
        shutil.rmtree(root)
    for sub in ("bin", "tests", "bench", "scenarios", "proc", "sys", "dev"):
        (root / sub).mkdir(parents=True)

    bb = find_busybox()
    shutil.copy2(bb, root / "bin/busybox")
    for applet in APPLETS:
        (root / "bin" / applet).symlink_to("busybox")

    shutil.copy2(repo / "kbuf.ko", root / "kbuf.ko")

    for src in sorted((repo / "tests").glob("*.c")):
        _check(["gcc", "-static", "-O2", f"-I{repo}/include",
                "-o", str(root / "tests" / src.stem), str(src)])
    for src in sorted((repo / "bench").glob("*.c")):
        _check(["gcc", "-static", "-O2", f"-I{repo}/include",
                "-o", str(root / "bench" / src.stem), str(src), "-lm"])

    for sh in sorted((repo / "verif" / "scenarios").glob("*.sh")):
        dst = root / "scenarios" / sh.name
        shutil.copy2(sh, dst)
        dst.chmod(0o755)

    init = root / "init"
    init.write_text(INIT)
    init.chmod(0o755)

    files = subprocess.run(
        ["find", ".", "-print0"], cwd=root, check=True, capture_output=True)
    cpio = subprocess.run(
        ["cpio", "--null", "-o", "--format=newc"], cwd=root,
        input=files.stdout, capture_output=True, check=True)
    gz = subprocess.run(["gzip", "-9"], input=cpio.stdout,
                        capture_output=True, check=True)
    out.write_bytes(gz.stdout)
    return out
